stages:
  - lint
  - test
  - build

image: marvinvanaalst/pixi-ci:0.1

prior:
  stage: lint
  script:
    - pixi run -e dev install
    - pixi run -e dev check
  except:
    - merge_requests
    - main

test:
  stage: test
  script:
    - pixi run -e dev install
    - pixi run -e dev test
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  only:
    - merge_requests
    - main # if i push directly and for coverage badge

build:
  stage: build
  script:
    - pixi run -e install
    - pixi run -e build
    - pixi run -e upload
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - pyproject.toml

pages:
  allow_failure: true
  stage: build
  script:
    - pixi run -e dev install
    - pixi run -e dev build-docs
  artifacts:
    paths:
      - public
  only:
    - main
