[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[project]
name = "parameteriser"
version = "0.1.0"
description = "Add a short description here"
authors = [
  {name = "Marvin van Aalst", email = "marvin.vanaalst@gmail.com"}
]

[tool]

[tool.mypy]
ignore_missing_imports = true

[tool.pixi.dependencies]
poetry = ">=1.8.2,<1.9"
ipykernel = ">=6.29.3,<6.30"
jupyter = ">=1.0.0,<1.1"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
parameteriser = {path = ".", editable = true}

[tool.pixi.system-requirements]
linux = "5.4.0"

[tool.pixi.tasks]
install = "poetry install"

[tool.poetry]
authors = ["Marvin van Aalst <marvin.vanaalst@gmail.com>"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "Intended Audience :: Science/Research",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Software Development",
  "Topic :: Scientific/Engineering",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX",
  "Operating System :: Unix",
  "Operating System :: MacOS",
  "Operating System :: OS Independent"
]
description = "FIXME"
documentation = "https://marvin.vanaalst.gitlab.io/parameteriser/"
keywords = ["FIXME"]
license = "GPL-3.0-or-later"
maintainers = ["Marvin van Aalst <marvin.vanaalst@gmail.com>"]
name = "Parameteriser"
readme = "README.md"
repository = "https://gitlab.com/marvin.vanaalst/parameteriser"
version = "0.1.0"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
typing-extensions = "^4.6.3"
zeep = "^4.2.1"
pandas = "^2.2.2"
scipy = "^1.13.0"
sspipe = "^0.1.17"
numpy = "^1.26.4"
matplotlib = "^3.8.4"
selenium = "^4.20.0"
beautifulsoup4 = "^4.12.3"
requests = "^2.31.0"

[tool.poetry.dev-dependencies]
ruff = "^0.4.2"
notebook = "^6.5.4"
jupyter_contrib_nbextensions = "^0.7.0"
pytest = "^7.4.0"
pytest-cov = "^4.1.0"

[tool.ruff]
include = ["*.py", "*.pyi", "**/pyproject.toml", "*.ipynb"]
line-length = 88
indent-width = 4

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "ANN101",
  "ANN401",
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D105",
  "D205",
  "D211",
  "D213",
  "D400",
  "D403",
  "D415",
  "E501",
  "S101",
  "S301",
  "S110",
  "N806",
  "PGH003",
  "PLR0913",
  "FIX001",
  "TD001",
  "TD002",
  "TD003",
  "TRY003",
  "PD901",
  "RUF100"
]
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []
